import type { Metadata } from 'next'
import {
  // Geist,
  // Geist_Mono,
  Inter,
  Manrope,
} from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${inter.variable} font-manrope antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
