[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerContext = "backend"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
ENVIRONMENT = "production"
