services:
  - type: web
    name: humanline-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: starter
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /health
