"""add_custom_text_fields_for_other_options

Revision ID: 4442e32d81b7
Revises: b19cb97a02aa
Create Date: 2025-10-03 12:58:46.836726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4442e32d81b7'
down_revision: Union[str, Sequence[str], None] = 'b19cb97a02aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('company_industry_other', sa.String(length=100), nullable=True, comment="Custom industry text when 'other' is selected"))
    op.add_column('onboarding', sa.Column('company_roles_other', sa.String(length=100), nullable=True, comment="Custom role text when 'other' is selected"))
    op.add_column('onboarding', sa.Column('your_needs_other', sa.String(length=200), nullable=True, comment="Custom needs text when 'other' is selected"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding', 'your_needs_other')
    op.drop_column('onboarding', 'company_roles_other')
    op.drop_column('onboarding', 'company_industry_other')
    # ### end Alembic commands ###
