"""Add email verification code field

Revision ID: 60923fa88c62
Revises: ebfd2309aa45
Create Date: 2025-10-01 15:14:09.264255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60923fa88c62'
down_revision: Union[str, Sequence[str], None] = 'ebfd2309aa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_code', sa.String(length=6), nullable=True, comment='6-digit verification code shown to users - maps to secure token'))
    op.create_index(op.f('ix_users_email_verification_code'), 'users', ['email_verification_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_code'), table_name='users')
    op.drop_column('users', 'email_verification_code')
    # ### end Alembic commands ###
