"""Add payroll fields and bank details

Revision ID: 8284404865f4
Revises: f1a2b3c4d5e6
Create Date: 2025-10-10 11:28:40.366552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8284404865f4'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the table exists before trying to drop the index
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    
    if 'employee_overtime_carryover' in inspector.get_table_names():
        # Only drop the index if the table exists
        try:
            op.drop_index(op.f('ix_employee_overtime_carryover_id'), table_name='employee_overtime_carryover')
        except Exception:
            # Index doesn't exist, continue
            pass
        op.drop_table('employee_overtime_carryover')
    op.add_column('employee_attendance', sa.Column('payroll_record_id', sa.Integer(), nullable=True))
    op.add_column('employee_attendance', sa.Column('period', sa.String(length=100), nullable=False))
    op.add_column('employee_attendance', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('employee_attendance', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.alter_column('employee_attendance', 'expected_hours',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='expected_hours::double precision')
    op.alter_column('employee_attendance', 'actual_work_hours',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='actual_work_hours::double precision')
    op.alter_column('employee_attendance', 'period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employee_attendance', 'period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'employee_attendance', 'employee_payroll_record', ['payroll_record_id'], ['id'])
    # Drop columns only if they exist
    columns_to_drop = ['late_arrivals', 'attendance_rate', 'days_present', 'days_absent', 'early_departures']
    for column in columns_to_drop:
        try:
            op.drop_column('employee_attendance', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    op.add_column('employee_bank_info', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('employee_bank_info', sa.Column('swift_bic', sa.String(length=11), nullable=True))
    op.add_column('employee_deficit', sa.Column('payroll_record_id', sa.Integer(), nullable=True))
    op.add_column('employee_deficit', sa.Column('deficit_hours', sa.String(length=50), nullable=True))
    op.add_column('employee_deficit', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('employee_deficit', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('employee_deficit', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('employee_deficit', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('employee_deficit', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.alter_column('employee_deficit', 'deficit_amount',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='deficit_amount::double precision')
    op.create_foreign_key(None, 'employee_deficit', 'employee_payroll_record', ['payroll_record_id'], ['id'])
    # Drop columns only if they exist
    deficit_columns_to_drop = ['period', 'status', 'reason', 'amount']
    for column in deficit_columns_to_drop:
        try:
            op.drop_column('employee_deficit', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    op.add_column('employee_overtime', sa.Column('payroll_record_id', sa.Integer(), nullable=True))
    op.add_column('employee_overtime', sa.Column('overtime_date', sa.Date(), nullable=False))
    op.add_column('employee_overtime', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('employee_overtime', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.alter_column('employee_overtime', 'overtime_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employee_overtime', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    # Drop constraint only if it exists
    try:
        op.drop_constraint(op.f('employee_overtime_approved_by_fkey'), 'employee_overtime', type_='foreignkey')
    except Exception:
        # Constraint doesn't exist, continue
        pass
    op.create_foreign_key(None, 'employee_overtime', 'employee_payroll_record', ['payroll_record_id'], ['id'])
    # Drop columns only if they exist
    overtime_columns_to_drop = ['approved_by', 'date']
    for column in overtime_columns_to_drop:
        try:
            op.drop_column('employee_overtime', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    op.add_column('employee_time_off', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('employee_time_off', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('employee_time_off', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('employee_time_off', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('employee_time_off', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.alter_column('employee_time_off', 'days_remaining',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # Drop constraint only if it exists
    try:
        op.drop_constraint(op.f('employee_time_off_approved_by_fkey'), 'employee_time_off', type_='foreignkey')
    except Exception:
        # Constraint doesn't exist, continue
        pass
    # Drop columns only if they exist
    time_off_columns_to_drop = ['status', 'reason', 'start_date', 'approved_by', 'end_date']
    for column in time_off_columns_to_drop:
        try:
            op.drop_column('employee_time_off', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time_off', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_time_off', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee_time_off', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_time_off', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employee_time_off', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employee_time_off_approved_by_fkey'), 'employee_time_off', 'users', ['approved_by'], ['id'])
    op.alter_column('employee_time_off', 'days_remaining',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('employee_time_off', 'meta_data')
    op.drop_column('employee_time_off', 'description')
    op.drop_column('employee_time_off', 'period_end')
    op.drop_column('employee_time_off', 'period_start')
    op.drop_column('employee_time_off', 'currency')
    op.add_column('employee_overtime', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_overtime', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_overtime', type_='foreignkey')
    op.create_foreign_key(op.f('employee_overtime_approved_by_fkey'), 'employee_overtime', 'users', ['approved_by'], ['id'])
    op.alter_column('employee_overtime', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_overtime', 'overtime_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('employee_overtime', 'meta_data')
    op.drop_column('employee_overtime', 'currency')
    op.drop_column('employee_overtime', 'overtime_date')
    op.drop_column('employee_overtime', 'payroll_record_id')
    op.add_column('employee_deficit', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('employee_deficit', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employee_deficit', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('employee_deficit', sa.Column('period', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_deficit', type_='foreignkey')
    op.alter_column('employee_deficit', 'deficit_amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('employee_deficit', 'meta_data')
    op.drop_column('employee_deficit', 'description')
    op.drop_column('employee_deficit', 'period_end')
    op.drop_column('employee_deficit', 'period_start')
    op.drop_column('employee_deficit', 'currency')
    op.drop_column('employee_deficit', 'deficit_hours')
    op.drop_column('employee_deficit', 'payroll_record_id')
    op.drop_column('employee_bank_info', 'swift_bic')
    op.drop_column('employee_bank_info', 'branch')
    op.add_column('employee_attendance', sa.Column('early_departures', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('days_absent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('days_present', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('attendance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('late_arrivals', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_attendance', type_='foreignkey')
    op.alter_column('employee_attendance', 'period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee_attendance', 'period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee_attendance', 'actual_work_hours',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('employee_attendance', 'expected_hours',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('employee_attendance', 'meta_data')
    op.drop_column('employee_attendance', 'description')
    op.drop_column('employee_attendance', 'period')
    op.drop_column('employee_attendance', 'payroll_record_id')
    op.create_table('employee_overtime_carryover',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_period_overtime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('used_this_period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remaining_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('carry_over_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_overtime_carryover_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_overtime_carryover_pkey'))
    )
    op.create_index(op.f('ix_employee_overtime_carryover_id'), 'employee_overtime_carryover', ['id'], unique=False)
    # ### end Alembic commands ###
