"""Add payroll fields and bank details

Revision ID: 8284404865f4
Revises: f1a2b3c4d5e6
Create Date: 2025-10-10 11:28:40.366552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8284404865f4'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the table exists before trying to drop the index
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    
    if 'employee_overtime_carryover' in inspector.get_table_names():
        # Only drop the index if the table exists
        try:
            op.drop_index(op.f('ix_employee_overtime_carryover_id'), table_name='employee_overtime_carryover')
        except Exception:
            # Index doesn't exist, continue
            pass
        op.drop_table('employee_overtime_carryover')
    
    # Create missing tables if they don't exist
    if 'employee_attendance' not in inspector.get_table_names():
        op.create_table('employee_attendance',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('employee_id', sa.Integer(), nullable=False),
            sa.Column('expected_hours', sa.Float(), nullable=False),
            sa.Column('actual_work_hours', sa.Float(), nullable=False),
            sa.Column('period_start', sa.Date(), nullable=True),
            sa.Column('period_end', sa.Date(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'employee_deficit' not in inspector.get_table_names():
        op.create_table('employee_deficit',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('employee_id', sa.Integer(), nullable=False),
            sa.Column('deficit_amount', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'employee_overtime' not in inspector.get_table_names():
        op.create_table('employee_overtime',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('employee_id', sa.Integer(), nullable=False),
            sa.Column('overtime_type', sa.String(length=50), nullable=True),
            sa.Column('description', sa.String(length=500), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'employee_time_off' not in inspector.get_table_names():
        op.create_table('employee_time_off',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('employee_id', sa.Integer(), nullable=False),
            sa.Column('days_remaining', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'employee_payroll_record' not in inspector.get_table_names():
        op.create_table('employee_payroll_record',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('employee_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
            sa.PrimaryKeyConstraint('id')
        )
    # Add columns only if they don't exist
    attendance_columns_to_add = [
        ('payroll_record_id', sa.Integer(), True),
        ('period', sa.String(length=100), False),
        ('description', sa.String(length=500), True),
        ('meta_data', sa.JSON(), True)
    ]
    for column_name, column_type, nullable in attendance_columns_to_add:
        try:
            op.add_column('employee_attendance', sa.Column(column_name, column_type, nullable=nullable))
        except Exception:
            # Column already exists, continue
            pass
    # Alter columns only if they exist and need modification
    try:
        op.alter_column('employee_attendance', 'expected_hours',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Float(),
                   existing_nullable=False,
                   postgresql_using='expected_hours::double precision')
    except Exception:
        pass
    
    try:
        op.alter_column('employee_attendance', 'actual_work_hours',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Float(),
                   existing_nullable=False,
                   postgresql_using='actual_work_hours::double precision')
    except Exception:
        pass
    
    try:
        op.alter_column('employee_attendance', 'period_start',
                   existing_type=sa.DATE(),
                   nullable=True)
    except Exception:
        pass
    
    try:
        op.alter_column('employee_attendance', 'period_end',
                   existing_type=sa.DATE(),
                   nullable=True)
    except Exception:
        pass
    # Create foreign key only if it doesn't exist
    try:
        op.create_foreign_key(None, 'employee_attendance', 'employee_payroll_record', ['payroll_record_id'], ['id'])
    except Exception:
        # Foreign key already exists, continue
        pass
    # Drop columns only if they exist
    columns_to_drop = ['late_arrivals', 'attendance_rate', 'days_present', 'days_absent', 'early_departures']
    for column in columns_to_drop:
        try:
            op.drop_column('employee_attendance', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    # Add bank info columns only if they don't exist
    bank_columns_to_add = [
        ('branch', sa.String(length=255), True),
        ('swift_bic', sa.String(length=11), True)
    ]
    for column_name, column_type, nullable in bank_columns_to_add:
        try:
            op.add_column('employee_bank_info', sa.Column(column_name, column_type, nullable=nullable))
        except Exception:
            # Column already exists, continue
            pass
    # Add deficit columns only if they don't exist
    deficit_columns_to_add = [
        ('payroll_record_id', sa.Integer(), True),
        ('deficit_hours', sa.String(length=50), True),
        ('currency', sa.String(length=3), False),
        ('period_start', sa.Date(), True),
        ('period_end', sa.Date(), True),
        ('description', sa.String(length=500), True),
        ('meta_data', sa.JSON(), True)
    ]
    for column_name, column_type, nullable in deficit_columns_to_add:
        try:
            op.add_column('employee_deficit', sa.Column(column_name, column_type, nullable=nullable))
        except Exception:
            # Column already exists, continue
            pass
    # Alter deficit amount column only if it exists
    try:
        op.alter_column('employee_deficit', 'deficit_amount',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Float(),
                   existing_nullable=False,
                   postgresql_using='deficit_amount::double precision')
    except Exception:
        pass
    # Create foreign key only if it doesn't exist
    try:
        op.create_foreign_key(None, 'employee_deficit', 'employee_payroll_record', ['payroll_record_id'], ['id'])
    except Exception:
        # Foreign key already exists, continue
        pass
    # Drop columns only if they exist
    deficit_columns_to_drop = ['period', 'status', 'reason', 'amount']
    for column in deficit_columns_to_drop:
        try:
            op.drop_column('employee_deficit', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    # Add overtime columns only if they don't exist
    overtime_columns_to_add = [
        ('payroll_record_id', sa.Integer(), True),
        ('overtime_date', sa.Date(), False),
        ('currency', sa.String(length=3), False),
        ('meta_data', sa.JSON(), True)
    ]
    for column_name, column_type, nullable in overtime_columns_to_add:
        try:
            op.add_column('employee_overtime', sa.Column(column_name, column_type, nullable=nullable))
        except Exception:
            # Column already exists, continue
            pass
    # Alter overtime columns only if they exist
    try:
        op.alter_column('employee_overtime', 'overtime_type',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
    except Exception:
        pass
    
    try:
        op.alter_column('employee_overtime', 'description',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.String(length=500),
                   existing_nullable=True)
    except Exception:
        pass
    # Drop constraint only if it exists
    try:
        op.drop_constraint(op.f('employee_overtime_approved_by_fkey'), 'employee_overtime', type_='foreignkey')
    except Exception:
        # Constraint doesn't exist, continue
        pass
    # Create foreign key only if it doesn't exist
    try:
        op.create_foreign_key(None, 'employee_overtime', 'employee_payroll_record', ['payroll_record_id'], ['id'])
    except Exception:
        # Foreign key already exists, continue
        pass
    # Drop columns only if they exist
    overtime_columns_to_drop = ['approved_by', 'date']
    for column in overtime_columns_to_drop:
        try:
            op.drop_column('employee_overtime', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    # Add time_off columns only if they don't exist
    time_off_columns_to_add = [
        ('currency', sa.String(length=3), False),
        ('period_start', sa.Date(), True),
        ('period_end', sa.Date(), True),
        ('description', sa.String(length=500), True),
        ('meta_data', sa.JSON(), True)
    ]
    for column_name, column_type, nullable in time_off_columns_to_add:
        try:
            op.add_column('employee_time_off', sa.Column(column_name, column_type, nullable=nullable))
        except Exception:
            # Column already exists, continue
            pass
    # Alter time_off column only if it exists
    try:
        op.alter_column('employee_time_off', 'days_remaining',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=True)
    except Exception:
        pass
    # Drop constraint only if it exists
    try:
        op.drop_constraint(op.f('employee_time_off_approved_by_fkey'), 'employee_time_off', type_='foreignkey')
    except Exception:
        # Constraint doesn't exist, continue
        pass
    # Drop columns only if they exist
    time_off_columns_to_drop = ['status', 'reason', 'start_date', 'approved_by', 'end_date']
    for column in time_off_columns_to_drop:
        try:
            op.drop_column('employee_time_off', column)
        except Exception:
            # Column doesn't exist, continue
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time_off', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_time_off', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee_time_off', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_time_off', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employee_time_off', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employee_time_off_approved_by_fkey'), 'employee_time_off', 'users', ['approved_by'], ['id'])
    op.alter_column('employee_time_off', 'days_remaining',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('employee_time_off', 'meta_data')
    op.drop_column('employee_time_off', 'description')
    op.drop_column('employee_time_off', 'period_end')
    op.drop_column('employee_time_off', 'period_start')
    op.drop_column('employee_time_off', 'currency')
    op.add_column('employee_overtime', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_overtime', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_overtime', type_='foreignkey')
    op.create_foreign_key(op.f('employee_overtime_approved_by_fkey'), 'employee_overtime', 'users', ['approved_by'], ['id'])
    op.alter_column('employee_overtime', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_overtime', 'overtime_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('employee_overtime', 'meta_data')
    op.drop_column('employee_overtime', 'currency')
    op.drop_column('employee_overtime', 'overtime_date')
    op.drop_column('employee_overtime', 'payroll_record_id')
    op.add_column('employee_deficit', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('employee_deficit', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employee_deficit', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('employee_deficit', sa.Column('period', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_deficit', type_='foreignkey')
    op.alter_column('employee_deficit', 'deficit_amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('employee_deficit', 'meta_data')
    op.drop_column('employee_deficit', 'description')
    op.drop_column('employee_deficit', 'period_end')
    op.drop_column('employee_deficit', 'period_start')
    op.drop_column('employee_deficit', 'currency')
    op.drop_column('employee_deficit', 'deficit_hours')
    op.drop_column('employee_deficit', 'payroll_record_id')
    op.drop_column('employee_bank_info', 'swift_bic')
    op.drop_column('employee_bank_info', 'branch')
    op.add_column('employee_attendance', sa.Column('early_departures', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('days_absent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('days_present', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('attendance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('employee_attendance', sa.Column('late_arrivals', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_attendance', type_='foreignkey')
    op.alter_column('employee_attendance', 'period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee_attendance', 'period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee_attendance', 'actual_work_hours',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('employee_attendance', 'expected_hours',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('employee_attendance', 'meta_data')
    op.drop_column('employee_attendance', 'description')
    op.drop_column('employee_attendance', 'period')
    op.drop_column('employee_attendance', 'payroll_record_id')
    op.create_table('employee_overtime_carryover',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_period_overtime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('used_this_period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remaining_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('carry_over_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_overtime_carryover_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_overtime_carryover_pkey'))
    )
    op.create_index(op.f('ix_employee_overtime_carryover_id'), 'employee_overtime_carryover', ['id'], unique=False)
    # ### end Alembic commands ###
