"""Add unique constraint to email_verification_code

Revision ID: 92e55afebdb6
Revises: ead7fea9d7c9
Create Date: 2025-10-01 21:24:18.160719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e55afebdb6'
down_revision: Union[str, Sequence[str], None] = 'ead7fea9d7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_code'), table_name='users')
    op.create_index(op.f('ix_users_email_verification_code'), 'users', ['email_verification_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_code'), table_name='users')
    op.create_index(op.f('ix_users_email_verification_code'), 'users', ['email_verification_code'], unique=False)
    # ### end Alembic commands ###
