"""add_onboarding_table

Revision ID: b22706b0b1e3
Revises: a225940b35bc
Create Date: 2025-10-03 11:57:47.726007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22706b0b1e3'
down_revision: Union[str, Sequence[str], None] = 'a225940b35bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_domain', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=False),
    sa.Column('company_industry', sa.String(length=100), nullable=False),
    sa.Column('company_roles', sa.String(length=100), nullable=False),
    sa.Column('your_needs', sa.String(length=200), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('workspace_created', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_domain'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_onboarding_id'), 'onboarding', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_id'), table_name='onboarding')
    op.drop_table('onboarding')
    # ### end Alembic commands ###
