"""Add comprehensive employee tables with relationships

Revision ID: c0a6da13d2c0
Revises: 3be6a6596f05
Create Date: 2025-10-07 22:52:10.370177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a6da13d2c0'
down_revision: Union[str, Sequence[str], None] = '3be6a6596f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_personal_details', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('employee_personal_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('employee_personal_details', 'gender',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'nationality',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'marital_status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'personal_tax_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'social_insurance_number',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'primary_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'city',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'state',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'country',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'postal_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_unique_constraint(None, 'employee_personal_details', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_personal_details', type_='unique')
    op.alter_column('employee_personal_details', 'postal_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'state',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'primary_address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'social_insurance_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'personal_tax_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'marital_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'nationality',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('employee_personal_details', 'updated_at')
    op.drop_column('employee_personal_details', 'created_at')
    # ### end Alembic commands ###
