"""add_nullable_needs_onboarding_field_to_users_table

Revision ID: cb1b89f6a33a
Revises: eb7be7a4f539
Create Date: 2025-10-05 15:18:51.459391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1b89f6a33a'
down_revision: Union[str, Sequence[str], None] = 'eb7be7a4f539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('needs_onboarding', sa.Boolean(), nullable=True, comment='Whether the user needs to complete onboarding process'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'needs_onboarding')
    # ### end Alembic commands ###
