"""Add IBAN field to employee bank info

Revision ID: d6dfdaad75c4
Revises: 8284404865f4
Create Date: 2025-10-10 15:12:11.836116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6dfdaad75c4'
down_revision: Union[str, Sequence[str], None] = '8284404865f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_bank_info', sa.Column('iban', sa.String(length=34), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_bank_info', 'iban')
    # ### end Alembic commands ###
