"""Remove long token, keep only 6-digit verification code

Revision ID: ead7fea9d7c9
Revises: 60923fa88c62
Create Date: 2025-10-01 15:20:56.128005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ead7fea9d7c9'
down_revision: Union[str, Sequence[str], None] = '60923fa88c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verification_code',
               existing_type=sa.VARCHAR(length=6),
               comment='6-digit verification code for email confirmation',
               existing_comment='6-digit verification code shown to users - maps to secure token',
               existing_nullable=True)
    op.alter_column('users', 'email_verification_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Email verification code expiration timestamp',
               existing_comment='Email verification token expiration timestamp',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_column('users', 'email_verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Token used for email verification - null after verification'))
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.alter_column('users', 'email_verification_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Email verification token expiration timestamp',
               existing_comment='Email verification code expiration timestamp',
               existing_nullable=True)
    op.alter_column('users', 'email_verification_code',
               existing_type=sa.VARCHAR(length=6),
               comment='6-digit verification code shown to users - maps to secure token',
               existing_comment='6-digit verification code for email confirmation',
               existing_nullable=True)
    # ### end Alembic commands ###
