"""remove_custom_other_fields

Revision ID: eb7be7a4f539
Revises: 4442e32d81b7
Create Date: 2025-10-04 14:19:20.716252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7be7a4f539'
down_revision: Union[str, Sequence[str], None] = '4442e32d81b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding', 'company_industry',
               existing_type=sa.VARCHAR(length=100),
               comment='Company industry (predefined or custom)',
               existing_comment='Company industry category',
               existing_nullable=False)
    op.alter_column('onboarding', 'company_roles',
               existing_type=sa.VARCHAR(length=100),
               comment="User's role in the company (predefined or custom)",
               existing_comment="User's role in the company",
               existing_nullable=False)
    op.alter_column('onboarding', 'your_needs',
               existing_type=sa.VARCHAR(length=200),
               comment='Primary HR system use case (predefined or custom)',
               existing_comment='Primary HR system use case',
               existing_nullable=False)
    op.drop_column('onboarding', 'company_industry_other')
    op.drop_column('onboarding', 'your_needs_other')
    op.drop_column('onboarding', 'company_roles_other')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('company_roles_other', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Custom role text when 'other' is selected"))
    op.add_column('onboarding', sa.Column('your_needs_other', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment="Custom needs text when 'other' is selected"))
    op.add_column('onboarding', sa.Column('company_industry_other', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Custom industry text when 'other' is selected"))
    op.alter_column('onboarding', 'your_needs',
               existing_type=sa.VARCHAR(length=200),
               comment='Primary HR system use case',
               existing_comment='Primary HR system use case (predefined or custom)',
               existing_nullable=False)
    op.alter_column('onboarding', 'company_roles',
               existing_type=sa.VARCHAR(length=100),
               comment="User's role in the company",
               existing_comment="User's role in the company (predefined or custom)",
               existing_nullable=False)
    op.alter_column('onboarding', 'company_industry',
               existing_type=sa.VARCHAR(length=100),
               comment='Company industry category',
               existing_comment='Company industry (predefined or custom)',
               existing_nullable=False)
    # ### end Alembic commands ###
